apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-user-app
  labels:  
    app: i27-user-app   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-user-app
  template:
    metadata:
      labels:
        app: i27-user-app
    spec:
      imagePullSecrets:  #used to pvt registry to pull the image that kept in scerte like regcred in thatsecrete jfrog connected information avaible
        - name: jfrog-secret
      containers:
      - name: i27-user-app
        image: DIT # this will be replaced by shared library
        ports:
        - containerPort: 8232
---
# Service 
apiVersion: v1
kind: Service           
metadata:
  name: i27-user-service
spec: 
  selector:
    app: i27-user-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8232
  type: NodePort