spring:
  application:
    name: learner-user-api

  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/product_managment?useSSL=false&allowPublicKeyRetrieval=true&sslMode=DISABLED&requireSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8232

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://136.113.39.247:3306/learnerCrownClothing?useSSL=false&allowPublicKeyRetrieval=true&sslMode=DISABLED&requireSSL=false&verifyServerCertificate=false&serverTimezone=UTC
    username: dbs_user
    password: Raghu@2025
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8232

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-dev.raghuprojectdevops.in/eureka/